### ISSUE TITLE
Customization of jacocoReportSettings isn't picked up

### ISSUE THREAD

**Issue by jypma** [sbt/sbt-jacoco#88]
### Expected vs Actual Behaviour

I'm upgrading a build to SBT 1.0 and, hence, sbt-jacoco 3.0.1. My `build.sbt` has 
```scala
jacocoExcludes := Seq("*data*") // don't do code coverage on generated protobuf classes
jacocoReportSettings := JacocoReportSettings().withFormats(JacocoReportFormats.XML)
```
which should trigger `sbt jacoco` to output XML instead of HTML, and ignore some packages. Neither setting is picked up; it always outputs HTML.

If I manually hack some values into `jacocoReport` directly, like
```scala
jacocoReport := com.github.sbt.jacoco.report.ReportUtils.generateReport(
      crossTarget.value / "jacoco" / "report",
      crossTarget.value / "jacoco" / "data" / "jacoco.exec",
      JacocoReportSettings().withFormats(JacocoReportFormats.XML),
      (sourceDirectories in Compile).value,
      Seq((classDirectory in Compile).value),
      JacocoSourceSettings(),
      streams.value
)
```
then it does start to output XML.

### Environment

* SBT version: 1.0.1
* Plugin version: 3.0.1
* Scala version(s): 2.12.3
* Java version: OpenJDK 1.8.0_144

I should mention that these settings are made in a sub-project's `build.sbt`, that's pulled into the root using
```
lazy val server = project in file("the-server") dependsOn xsd
lazy val root = (project in file(".")).aggregate(server, xsd)
```
but I don't see how that would affect things...

**Comment by Z1kkurat** [comment]
I observe the same problem - I have  two subprojects. In each one I have settings as follows:
```scala
jacocoReportSettings := JacocoReportSettings().withThresholds(JacocoThresholds(method = 80.0, line = 80.0)
```
Still when I call `subproject1/jacoco` or `subproject2/jacoco` nothing happens and it's still `>= required 0.0%` in console report.

**Comment by stringbean** [comment]
This is due to the settings only getting set for your root project and not the aggregated projects. 

You will need to make the settings common by passing them [into the project](http://www.scala-sbt.org/1.x/docs/Multi-Project.html#Common+settings) or by using [build-wide settings](http://www.scala-sbt.org/1.x/docs/Multi-Project.html#Build-wide+settings).

**Comment by Z1kkurat** [comment]
@jypma If you're having the same issue as me, I managed to overcome this by specifying `in Test` for `jacocoReportSettings`.
So my build.sbt is looking like the following:
```scala
lazy val commonSettings = Seq(
  version := "1.0",
  scalaVersion := "2.12.3"
)

lazy val scalatest = Seq(
  libraryDependencies ++= Seq(
    "org.scalactic" %% "scalactic" % "3.0.1",
    "org.scalatest" %% "scalatest" % "3.0.1" % Test
  )
)

lazy val jacoco = Seq(
  jacocoReportSettings in Test := JacocoReportSettings()
    .withFileEncoding("UTF-8")
    .withThresholds(JacocoThresholds(method = 90.0, line = 90.0))
)

lazy val root = project
  .in(file("."))
  .aggregate(module1, module2)

lazy val module1 =
  project
    .in(file("module1"))
    .settings(commonSettings)
    .settings(scalatest)
    .settings(jacoco)

lazy val module2 =
  project
    .in(file("module2"))
    .settings(commonSettings)
    .settings(scalatest)
    .settings(jacoco)
```
Docs for this behaviour would be really cool.
And all parameters from `JacocoReportSettings` work fine for all projects.
But now I encountered another issue: if there is no code at all in project (neither in `src/main` nor `src/test`, calling `module2/jacoco` on that project fails with `Required coverage is not met`). 
 @stringbean should I submit an issue about that or it's an expected behaviour?

**Comment by stringbean** [comment]
It should no longer be necessary to specify `in Test` for the settings from 3.0.3 onwards.
